### ISSUE TITLE
Having trouble creating deployment pipeline in EKS using your Dockerfile

### ISSUE THREAD

**Issue by Aniket-devopss** [nickjj/docker-phoenix-example#14]
I am trying to create Deployment pipeline in EKS that will deploy your application setup in Kubernetes. but i am stuck at running the container from Docker i am getting the following error "cp : cannot create directory '/app/priv/static': no such file or directory "
![image (1)](https://github.com/nickjj/docker-phoenix-example/assets/167755182/28c7edad-f405-4fa1-bd2c-3dcb879e166c)
also when i try using docker compose build command and then run the image to make containers i am getting error "mkdir : cannot create directory '../priv/static/css' : permission denied "  and "mkdir : cannot create directory '../priv/static/js' : permission denied " 
![image (2)](https://github.com/nickjj/docker-phoenix-example/assets/167755182/77687b9d-a486-4d44-befd-f1b0b905da8d)

**Comment by nickjj** [comment]
Hi,

For the Docker Compose issue, did you follow this troubleshooting guide from the readme file?

> Did you receive a permission denied error? Chances are you're running native Linux and your `uid:gid` aren't `1000:1000` (you can verify this by running `id`). Check out the docs in the `.env` file to customize the `UID` and `GID` variables to fix this.

For Kubernetes, it's expected you wouldn't be using volumes. Did you set up a volume?

**Comment by Aniket-devopss** [comment]
yes for docker-compose i followed the readme file and i am not using volumes for kubernetes , first i am just trying to run container using dockerfile if that goes well i will be moving with whole setup on kubernetes also and can you elaborate on how runtime.exe comes into play.

**Comment by nickjj** [comment]
Ok, what's the result of running `id` on your Docker Compose set up's box? Paste the output here please.

**Comment by Aniket-devopss** [comment]
![image](https://github.com/nickjj/docker-phoenix-example/assets/167755182/9ec42794-c037-4f0d-9c3b-3387cf59716d)

**Comment by nickjj** [comment]
Did you run your Docker Compose commands as root at some point? I don't see `docker` in the output. 

What's the output of running `ls -la ~/git/docker-phoenix/example`?

**Comment by Aniket-devopss** [comment]
i have resolved the cp : cannot create directory '/app/priv/static error by making changes in .env and docker-entrypoint-web file.
[docker-entrypoint-web.txt](https://github.com/nickjj/docker-phoenix-example/files/15065397/docker-entrypoint-web.txt)
[env_task.txt](https://github.com/nickjj/docker-phoenix-example/files/15066489/env_task.txt)
but now i am getting different error 
![image](https://github.com/nickjj/docker-phoenix-example/assets/167755182/d20ff4d4-2d7d-4bec-9f01-50e3e39b9698)

and for above yes i used docker compose commands root user before.

**Comment by nickjj** [comment]
If they're owned by root and now you try to run commands without root then yes, you'll get file permission errors. This is independent of this project or Docker. You'll want to make all of the files owned by your user and then run your Docker commands as that user.

You shouldn't need to make any code edits. That entrypoint change you made will break your assets in production btw. They will never get the latest built copy.

**Comment by Aniket-devopss** [comment]
Hy @nickjj, now I'm trying with a Dockerfile. I successfully built the image, and after that, I created a PostgreSQL container with this command - docker run --name postgres   --hostname postgres  -e POSTGRES_PASSWORD=password   -e POSTGRES_USER=db_user  -p 5432  -d   postgres...............but I am still getting error from application container. It look like this 11:02:47.898 [error] Postgrex.Protocol (#PID<0.1936.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (postgres:5432): non-existing domain - :nxdomain

**Comment by nickjj** [comment]
This project sets up Postgres for you in the Docker Compose file, you don't need to run it manually.

If you want to run a different Postgres container you'll want to run it with the `--network` flag and set it to be the same network as this project creates, which will depend on the project name, but you can run `docker network ls` to find it. This is unrelated to this project btw, this is how networking works with Docker.

**Comment by Aniket-devopss** [comment]
@nickjj I am using the same network which is bridge, and I want to deploy it in Kubernetes; that's why I'm not using Docker Compose.

**Comment by Aniket-devopss** [comment]
I think there is something wrong with the command docker run --name postgres --hostname postgres -e POSTGRES_PASSWORD=password -e POSTGRES_USER=db_user -p 5432 -d postgres as per environment...can you make it for me.

**Comment by nickjj** [comment]
The command you're running is to run a container using Docker, not Kubernetes.

You'd want to add the `--network=XXX` flag where `XXX` is the output of the network name created for your project which is dependent on what you named the project. You can find it with `docker network ls`. However, this is unrelated to Kubernetes, this is if you wanted to run Postgres separately from this project.

If you want to run a database in Kubernetes, that's beyond the scope of what I can offer here in this issue. That's really dependent on what your knowledge is about Kubernetes and what you want to accomplish.

**Comment by Aniket-devopss** [comment]
@nickjj I have deployed an application on Kubernetes, and it is working fine. However, when I try to connect to the database, I encounter an error...

ERROR! Config provider Config.Reader failed with:
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a textual representation of an integer

    :erlang.binary_to_integer("tcp://10.96.174.248:5432")
    /app/releases/0.1.0/runtime.exs:37: (file)
    (elixir 1.16.2) src/elixir.erl:405: :elixir.eval_external_handler/3
    (stdlib 5.2.2) erl_eval.erl:750: :erl_eval.do_apply/7
    (stdlib 5.2.2) erl_eval.erl:1026: :erl_eval.expr_list/7
    (stdlib 5.2.2) erl_eval.erl:292: :erl_eval.expr/6
    (stdlib 5.2.2) erl_eval.erl:282: :erl_eval.expr/6
    (stdlib 5.2.2) erl_eval.erl:283: :erl_eval.expr/6

Runtime terminating during boot ({badarg,[{erlang,binary_to_integer,[<<"tcp://10.96.174.248:5432">>],[{error_info,#{module=>erl_erts_errors}}]},{elixir_eval,'__FILE__',1,[{file,"/app/releases/0.1.0/runtime.exs"},{line,37}]},{elixir,eval_external_handler,3,[{file,"src/elixir.erl"},{line,405}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,750}]},{erl_eval,expr_list,7,[{file,"erl_eval.erl"},{line,1026}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,292}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,282}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,283}]}]})

Crash dump is being written to: erl_crash.dump...done

without Database it is working fine.

**Comment by nickjj** [comment]
Hi,

Sorry, I'm not going to be able to offer support for a custom application running in Kubernetes.

If it works without the database then chances are something about your DB's configuration is invalid or the host is unreachable. I don't know how you have your app configured but the error suggests it expects you pass in an integer but you're passing in a string.

If you look at the stack trace, it references `runtime.exs` line 37. If you're using the config that comes with this starter project that line expects you to pass in the DB port number, not the protocol + host + port.
